# Generated by Django 5.2.4 on 2025-07-16 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='location name')),
                ('addres', models.CharField(max_length=256, verbose_name='location addres')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='location description')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Notbad'), (3, 'Good'), (4, 'Verygood'), (5, 'Exellent')])),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Notbad'), (3, 'Good'), (4, 'Verygood'), (5, 'Exellent')])),
                ('comment', models.TextField(max_length=512, verbose_name='review comment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_reviews.location', verbose_name='connected location')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
    ]
