# Generated by Django 5.2.4 on 2025-07-16 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='category name')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='number of dislikes'),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='number of likes'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='review author'),
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Nocomments'), (1, 'Poor'), (2, 'Notbad'), (3, 'Good'), (4, 'Verygood'), (5, 'Exellent')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='addres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_reviews.address', verbose_name='location address'),
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='location_reviews.locationcategories', verbose_name='location category'),
        ),
    ]
