# Generated by Django 5.2.4 on 2025-07-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_reviews', '0002_address_locationcategories_review_dislikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='addres',
            new_name='address',
        ),
    ]
