# Generated by Django 5.2.4 on 2025-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_reviews', '0003_rename_addres_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(null=True, to='location_reviews.locationcategories', verbose_name='location categories'),
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Nocomments'), (1, 'Poor'), (2, 'Notbad'), (3, 'Good'), (4, 'Verygood'), (5, 'Exellent')], default=0),
        ),
    ]
