# Generated by Django 5.2.4 on 2025-07-16 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_reviews', '0005_alter_review_location_alter_review_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_reviews.location', verbose_name='connected location'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='review author'),
        ),
    ]
