# Generated by Django 5.2.4 on 2025-07-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_reviews', '0006_alter_review_location_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pk']},
        ),
    ]
